### ISSUE TITLE
Mybema's Goal

### ISSUE THREAD

**Issue by nahtnam** [mybema/mybema#12]
Hey!

I was wondering what mybemas goal was. It says it wants to be a `community platform` but what kind? Does it want to be a community platform for business to use (support, FAQ, questions, etc), or does it want to be sort of like a public forum?

Thanks.

**Comment by pawel2105** [comment]
Hey @nahtnam 

The goal of the project is for business and organizations (like local meetup groups, sports clubs etc.) to be able to run their own communities on their own servers. So a company like Example Inc. with the site example.com can run a community using Mybema on community.example.com - for instance. Yep, you can use this platform for things like discussions, customer support, answering questions, and writing up knowledgebase articles that serve as a FAQ replacement.

If you want you can even set up a Mybema instance on your intranet to serve as a way for your company to have discussions and share knowledge internally (althought that isn't the primary goal).

That being said, http://community.mybema.com is an instance of Mybema I've set up and manage whose aim is to share knowledge around community management and community strategy.

Hope that answers your question?

**Comment by nahtnam** [comment]
@pawel2105 This is pretty much exactly what I was looking for. An open source knowledgebase/community platform for my website (based in ruby on rails). All thats left to find is an open source customer support service! :P

**Comment by pawel2105** [comment]
@nahtnam can I recommend https://getbrimir.com/ ? It may be what you're looking for ;) If you plan on using Mybema, ping me if you have any questions. I'll probably make a wiki page for people to add their startups or projects if they use Mybema.

**Comment by nahtnam** [comment]
@pawel2105 Ill check out brimir. Ill probably use mybema, but my site is still in development so it may take a month or so to get everything running.
